### ISSUE TITLE
RSpec deprecation warnings

### ISSUE THREAD

**Issue by threedaymonk** [damian/jshint#19]
RSpec is specified in the gemspec as `~> 2.14`. This currently resolves to `2.99.0`, which includes deprecation warnings for RSpec 3.

I suggest either:

1. Change the dependency to add `< 2.99` (i.e. `spec.add_development_dependency "rspec", "~> 2.14", "< 2.99"`)
2. Fix the deprecation warnings and upgrade to RSpec 3.

I'd be happy to submit a pull request for either of these.

**Comment by damian** [comment]
Good shout. I'd prefer to upgrade to RSpec 3. I'd gladly accept a PR to achieve this if your able to :+1:
