### ISSUE TITLE
can't exclude app paths with `exclude_paths` 

### ISSUE THREAD

**Issue by benwalsh** [damian/jshint#28]
If I try:

```
exclude_paths: ['app/assets/javascripts/i18n','vendor/assets/javascripts']
```

or just:

```
exclude_paths: ['app/assets/javascripts/i18n']
```

The `i18n` directory still gets checked. The `vendor` stuff is excluded, no problem. Do I need to change the `files` declaration also?

**Comment by GolfyMcG** [comment]
I am having a VERY similar issue. Tried all manner of combinations of things with a directory inside of my javascripts directory and it did not exclude it.

**Comment by damian** [comment]
Sorry about this folks - I can see how this would be causing you some pain based on the example you provided.

I'll see what I can do about this to make it more flexible - rest assured I'll get something together to fix this :smile:

**Comment by damian** [comment]
This has been addressed in [this PR](https://github.com/damian/jshint/pull/40). Sorry for the wait :(
