### ISSUE TITLE
Adding additional files doesn't work

### ISSUE THREAD

**Issue by nevesenin** [damian/jshint#32]
Hi,

I tried to add `spec/javascripts/**/*.js` to files configuration, but it didn't work as expected. I wrote as test, to show what went wrong:
https://github.com/nevesenin/jshint/commit/5b287b3582952d4ab55e6e9107f01345233bebb1
I did not write a fix for that because I think there is more than one way to fix it. For my part, I would prefer a file name pattern configuration with `*.js` as default and a search paths configuration.
As a workaround I added `../../../spec/javascripts/*.js` to files configuration. The files are linted three times now, but this is better then never.

**Comment by damian** [comment]
I've just release v1.4.0 containing [a fix for this](https://github.com/damian/jshint/commit/9725c95c8711bfa1b069e63fe0f95fafe21f4503) - thanks for bringing this to my attention.

Can you confirm that this resolves your issue?

**Comment by nevesenin** [comment]
Yes, it works. Thank you!! :thumbsup:

**Comment by damian** [comment]
Happy days. No problem 👍🏻
