### ISSUE TITLE
Exclude single files

### ISSUE THREAD

**Issue by meacuna** [damian/jshint#38]
It would be helpful to be able to exclude single files.

For example:

``` bash
app/assets/javascripts/foo.js
app/assets/javascripts/unmantained_but_useful.js
...
```

In this case I would like to lint all my files in `app/assets/javascripts` except some old, unmaintained but useful file.

**Comment by damian** [comment]
This has been addressed in [this PR](https://github.com/damian/jshint/pull/40).
