### ISSUE TITLE
Run the check with javascript files I want to choose

### ISSUE THREAD

**Issue by tianhao-au** [damian/jshint#8]
In your document, you said "This Rake task runs JSHint across all the JavaScript assets within the following three folders to ensure that they're lint free.
your-rails-project/app/assets/javascripts
your-rails-project/vendor/assets/javascripts
your-rails-project/lib/assets/javascripts"

How can we use the regex to include and exclude some javascript files?

Is that possible? Thanks.

**Comment by svbergerem** [comment]
@damian: How do you check files in `rails-project/spec/javascripts/*`? @ysihaoy already asked this question but got no answer.
